export const START_UPLOAD = "START_UPLOAD";
export const UPLOAD_FINISHED = "UPLOAD_FINISHED";
export const UPLOAD_FAILED = "UPLOAD_FAILED";
export const OPEN_CREATE_PLATE_STANDALONE = "OPEN_CREATE_PLATE";
export const PLATE_CREATED = "PLATE-CREATED";

export const {
    ELECTRON_WEBPACK_APP_LIMS_PROTOCOL: LIMS_PROTOCOL = "http",
    ELECTRON_WEBPACK_APP_LIMS_HOST: LIMS_HOST = "localhost",
    ELECTRON_WEBPACK_APP_LIMS_PORT: LIMS_PORT = "8080",
    NODE_ENV,
} = process.env;
